import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erenk
 */
public class Hosgeldiniz extends javax.swing.JFrame implements Fiyat{
      DefaultTableModel model;
    /**
     * Creates new form Hosgeldiniz
     */
    public Hosgeldiniz() {
        initComponents();
        model=(DefaultTableModel) jFilmTable.getModel();
      
        try {
            ArrayList<Films> filmses = getFilmses();
            for(Films films : filmses){
                Object[] row = {
                    films.getFilmadi(),
                    films.getFilmtürü(),
                    films.getFilmyonetmeni(),
                    films.getFilmseansi(),
                    films.getFilmid()
                    };
                model.addRow(row);
            }
        } catch(SQLException ex) {
           System.out.println(ex);
        }
    }

    @Override
    public String getBilet() {
        return "Fiyat 16 Tl'dir"; 
    }
    ;
    
    public ArrayList<Films> getFilmses() throws SQLException{
        Connection connection=null;
        DbHelper dbHelper = new  DbHelper();
        Statement statement=null;
        ResultSet resultSet;
        ArrayList<Films> filmses= null;
        
        try{
            connection=dbHelper.getConnection();
            statement=connection.createStatement();
            resultSet = statement.executeQuery("select * from filmler");
            filmses= new ArrayList<Films>();
            
            while(resultSet.next()){
                filmses.add(new Films(
                                              resultSet.getString("filmadi"),
                                              resultSet.getString("filmtürü"),
                                              resultSet.getString("filmyonetmeni"),
                                              resultSet.getString("filmseansi"),
                                              resultSet.getString("filmid")
                                              ));
            }
        }catch(SQLException exception){
            dbHelper.showErrorMessage(exception);
        }finally{
                statement.close();
                connection.close();
                
        }
        return filmses;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFilmTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtSearchKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTxtAd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtSoyad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtKoltuk = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(938, 539));
        setMinimumSize(new java.awt.Dimension(938, 539));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(938, 539));
        jPanel1.setMinimumSize(new java.awt.Dimension(938, 539));
        jPanel1.setPreferredSize(new java.awt.Dimension(938, 539));
        jPanel1.setLayout(null);

        jFilmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Film Adı", "Film Türü", "Yönetmen", "Seanslar", "Film ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jFilmTable);
        if (jFilmTable.getColumnModel().getColumnCount() > 0) {
            jFilmTable.getColumnModel().getColumn(0).setResizable(false);
            jFilmTable.getColumnModel().getColumn(1).setResizable(false);
            jFilmTable.getColumnModel().getColumn(2).setResizable(false);
            jFilmTable.getColumnModel().getColumn(3).setResizable(false);
            jFilmTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 80, 736, 93);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("GAZİ SİNEMA SALONUNA HOŞ GELDİNİZ !");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 30, 548, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Filtrelemek istediğiniz kelimeyi yazınız           :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 224, 274, 15);

        jTxtSearchKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtSearchKeyKeyReleased(evt);
            }
        });
        jPanel1.add(jTxtSearchKey);
        jTxtSearchKey.setBounds(290, 220, 540, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Giriş yapmak istediğiniz film ID'sini yazınız    :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 276, 277, 15);

        jTxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtId);
        jTxtId.setBounds(290, 270, 540, 30);

        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(1070, 341, 0, 0);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BİLET AL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 330, 236, 57);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AD :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 340, 31, 23);

        jTxtAd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAdActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtAd);
        jTxtAd.setBounds(100, 340, 115, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("SOYAD :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 390, 67, 17);

        jTxtSoyad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTxtSoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSoyadActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtSoyad);
        jTxtSoyad.setBounds(100, 390, 115, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("KOLTUK NO:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 440, 104, 17);
        jPanel1.add(jTxtKoltuk);
        jTxtKoltuk.setBounds(100, 440, 117, 30);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("BOŞ KOLTUKLARI GÖR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 420, 236, 56);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sinemaicon2.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 300, 318, 228);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sinemaicon8.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 11, 264, 193);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtSearchKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtSearchKeyKeyReleased
        String searchKey=jTxtSearchKey.getText();
        TableRowSorter<DefaultTableModel> tableRowSorter = new  TableRowSorter<DefaultTableModel>(model);
        jFilmTable.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(searchKey));
    }//GEN-LAST:event_jTxtSearchKeyKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jTxtKoltuk.getText().equals("a1") || jTxtKoltuk.getText().equals("a2") || jTxtKoltuk.getText().equals("a3") || jTxtKoltuk.getText().equals("a4") ||
                   jTxtKoltuk.getText().equals("b1") || jTxtKoltuk.getText().equals("b2") || jTxtKoltuk.getText().equals("b3") || jTxtKoltuk.getText().equals("b4") ||
                        jTxtKoltuk.getText().equals("c1") || jTxtKoltuk.getText().equals("c2") || jTxtKoltuk.getText().equals("c3") || jTxtKoltuk.getText().equals("c4") ||
                            jTxtKoltuk.getText().equals("d1") || jTxtKoltuk.getText().equals("d2") || jTxtKoltuk.getText().equals("d3") || jTxtKoltuk.getText().equals("d4")){
           
           if(jTxtId.getText().equals("1") || jTxtId.getText().equals("2") || jTxtId.getText().equals("3") || jTxtId.getText().equals("4")){
        Connection connection=null;
        DbHelper dbHelper = new  DbHelper();
        PreparedStatement statement = null;
        Statement statement2=null;
        ResultSet resultSet;
        int dogrulama=0;
       try{
           connection=dbHelper.getConnection();
           
           if(jTxtId.getText().equals("1")){
                String sql2="select * from bilet where filmid='1'";
                  statement2=connection.createStatement();
                  resultSet=statement2.executeQuery(sql2);
                  ArrayList<String> arrayList = new ArrayList<String>();
                   while(resultSet.next()){
                      arrayList.add(resultSet.getString("koltukno"));
                  }
                   for(Object object:arrayList){
                                              if(object.equals(jTxtKoltuk.getText())){
                           JOptionPane.showMessageDialog(this,"Dolu koltuk seçtiniz. Lütfen boş koltuklardan birini seçiniz");
                           dogrulama++;
                           
                       }
                   }
           }
           else if(jTxtId.getText().equals("2")){
               String sql2="select * from bilet where filmid='2'";
                  statement2=connection.createStatement();
                  resultSet=statement2.executeQuery(sql2);
                  ArrayList<String> arrayList2 = new ArrayList<String>();
                   while(resultSet.next()){
                      arrayList2.add(resultSet.getString("koltukno"));
                  }
                   for(Object object:arrayList2){
                       
                       if(object.equals(jTxtKoltuk.getText())){
                           JOptionPane.showMessageDialog(this,"Dolu koltuk seçtiniz. Lütfen boş koltuklardan birini seçiniz");
                           dogrulama++;
                       }
                   }
           }
           else if(jTxtId.getText().equals("3")){
               String sql2="select * from bilet where filmid='3'";
                  statement2=connection.createStatement();
                  resultSet=statement2.executeQuery(sql2);
                  ArrayList<String> arrayList3 = new ArrayList<String>();
                   while(resultSet.next()){
                      arrayList3.add(resultSet.getString("koltukno"));
                  }
                   for(Object object:arrayList3){
                      
                                              if(object.equals(jTxtKoltuk.getText())){
                           JOptionPane.showMessageDialog(this,"Dolu koltuk seçtiniz. Lütfen boş koltuklardan birini seçiniz");
                           dogrulama++;
                       }
                                            
                   }
           }
            else if(jTxtId.getText().equals("4")){
               String sql2="select * from bilet where filmid='4'";
                  statement2=connection.createStatement();
                  resultSet=statement2.executeQuery(sql2);
                  ArrayList<String> arrayList4 = new ArrayList<String>();
                   while(resultSet.next()){
                      arrayList4.add(resultSet.getString("koltukno"));
                  }
                   for(Object object:arrayList4){
                      
                                              if(object.equals(jTxtKoltuk.getText())){
                           JOptionPane.showMessageDialog(this,"Dolu koltuk seçtiniz. Lütfen boş koltuklardan birini seçiniz");
                           dogrulama++;
                       }
                                            
                   }
           }
           
          
          if(dogrulama!=1){
              
           String sql="insert into bilet(ad,soyad,koltukno,filmid,ACTIVE) values(?,?,?,?,1)";
           statement=connection.prepareStatement(sql);
           statement.setString(1,jTxtAd.getText());
           statement.setString(2,jTxtSoyad.getText());
           statement.setString(3,jTxtKoltuk.getText().toLowerCase());
           statement.setString(4,jTxtId.getText());
           int result=statement.executeUpdate();
           String filmId=jTxtId.getText();
           
           JOptionPane.showMessageDialog(this,getBilet());
           dogrulama=0;
          }
           
       }   catch (SQLException ex) { 
               System.out.println(ex);
           }       
           }
       
          
       }
       else {
           JOptionPane.showMessageDialog(this,"Lütfen geçerli bir koltuk numarası veya Id giriniz!");
           }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtSoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSoyadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(jTxtId.getText().equals("1")){
       Salon1 salon1 = new Salon1();
       salon1.setVisible(true);
       salon1.pack();
       salon1.setLocationRelativeTo(null);
       salon1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
                 Connection connection=null;
              DbHelper dbHelper= new DbHelper();
              Statement statement=null;
              ResultSet resultSet;
              try{
                  connection=dbHelper.getConnection();
                  String sql="select * from bilet where filmid='1'";
                  statement=connection.createStatement();
                  resultSet=statement.executeQuery(sql);
                  ArrayList<String> arrayList = new ArrayList<String>();
                  int sayac=0;
                  while(resultSet.next()){
                      arrayList.add(resultSet.getString("koltukno"));
                      sayac++;
                  }
                 for(Object object:arrayList){
                    try{
                         if(object.equals("a1")){
                             
                         salon1.jButtonA1.setBackground(Color.white);
                       
                     }
                           if(object.equals("a2")){
                         salon1.jButtonA2.setBackground(Color.white);
                     }
                             if(object.equals("a3")){
                         salon1.jButton3.setBackground(Color.white);
                     }
                               if(object.equals("a4")){
                         salon1.jButton4.setBackground(Color.white);
                     }     if(object.equals("b1")){
                         salon1.jButton5.setBackground(Color.white);
                                 }
                           if(object.equals("b2")){
                         salon1.jButton6.setBackground(Color.white);
                     }
                             if(object.equals("b3")){
                         salon1.jButton7.setBackground(Color.white);
                     }
                               if(object.equals("b4")){
                         salon1.jButton8.setBackground(Color.white);
                     }
                                 if(object.equals("c1")){
                         salon1.jButton9.setBackground(Color.white);
                     }
                         if(object.equals("c2")){
                             salon1.jButton10.setBackground(Color.white);
                         }
                           if(object.equals("c3")){
                         salon1.jButton11.setBackground(Color.white);
                     }
                             if(object.equals("c4")){
                         salon1.jButton12.setBackground(Color.white);
                     }
                               if(object.equals("d1")){
                         salon1.jButton13.setBackground(Color.white);
                     }else{
                             salon1.jButton13.setBackground(Color.red);
                         }
                                 if(object.equals("d2")){
                         salon1.jButton14.setBackground(Color.white);
                     }
                                   if(object.equals("d3")){
                         salon1.jButton15.setBackground(Color.white);
                     }
                                     if(object.equals("d4")){
                         salon1.jButton16.setBackground(Color.white);
                     }
                    }catch(Exception exception){
                             System.out.print(exception);
                             }
                    }
                 
              } catch (SQLException ex) {
                   System.out.println(ex);
                }finally{
            try {
                connection.close();
                statement.close();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
              }
       
       }
       else if(jTxtId.getText().equals("2")){
           Salon2 salon2 = new Salon2();
       salon2.setVisible(true);
       salon2.pack();
       salon2.setLocationRelativeTo(null);
       salon2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
         Connection connection=null;
              DbHelper dbHelper= new DbHelper();
              Statement statement=null;
              ResultSet resultSet;
              try{
                  connection=dbHelper.getConnection();
                  String sql="select * from bilet where filmid='2'";
                  statement=connection.createStatement();
                  resultSet=statement.executeQuery(sql);
                  ArrayList<String> arrayList = new ArrayList<>();
                  int sayac=0;
                  while(resultSet.next()){
                      arrayList.add(resultSet.getString("koltukno"));
                      sayac++;
                  }
                 for(Object object:arrayList){
                    try{
                         if(object.equals("a1")){
                         salon2.jButton1.setBackground(Color.white);
                     }
                           if(object.equals("a2")){
                         salon2.jButton2.setBackground(Color.white);
                     }
                             if(object.equals("a3")){
                         salon2.jButton3.setBackground(Color.white);
                     }
                               if(object.equals("a4")){
                         salon2.jButton4.setBackground(Color.white);
                     }
                                 if(object.equals("b1")){
                         salon2.jButton5.setBackground(Color.white);
                                 }
                           if(object.equals("b2")){
                         salon2.jButton6.setBackground(Color.white);
                     }
                             if(object.equals("b3")){
                         salon2.jButton7.setBackground(Color.white);
                     }
                               if(object.equals("b4")){
                         salon2.jButton8.setBackground(Color.white);
                     }
                                 if(object.equals("c1")){
                         salon2.jButton9.setBackground(Color.white);
                     }
                         if(object.equals("c2")){
                             salon2.jButton10.setBackground(Color.white);
                         }
                           if(object.equals("c3")){
                         salon2.jButton11.setBackground(Color.white);
                     }
                             if(object.equals("c4")){
                         salon2.jButton12.setBackground(Color.white);
                     }
                               if(object.equals("d1")){
                         salon2.jButton13.setBackground(Color.white);
                     }
                                 if(object.equals("d2")){
                         salon2.jButton14.setBackground(Color.white);
                     }
                                   if(object.equals("d3")){
                         salon2.jButton15.setBackground(Color.white);
                     }
                                     if(object.equals("d4")){
                         salon2.jButton16.setBackground(Color.white);
                     }
                    }catch(Exception exception){
                             System.out.print(exception);
                             }
                    }
                 
              } catch (SQLException ex) {
                   System.out.println(ex);
                }finally{
            try {
                connection.close();
                statement.close();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
              }
       }
       else if(jTxtId.getText().equals("3")){
       Salon3 salon3 = new Salon3();
       salon3.setVisible(true);
       salon3.pack();
       salon3.setLocationRelativeTo(null);
       salon3.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
        Connection connection=null;
              DbHelper dbHelper= new DbHelper();
              Statement statement=null;
              ResultSet resultSet;
              try{
                  connection=dbHelper.getConnection();
                  String sql="select * from bilet where filmid='3'";
                  statement=connection.createStatement();
                  resultSet=statement.executeQuery(sql);
                  ArrayList<String> arrayList = new ArrayList<>();
                  int sayac=0;
                  while(resultSet.next()){
                      arrayList.add(resultSet.getString("koltukno"));
                      sayac++;
                  }
                 for(Object object:arrayList){
                    try{
                         if(object.equals("a1")){
                         salon3.jButton1.setBackground(Color.white);
                     }
                           if(object.equals("a2")){
                         salon3.jButton2.setBackground(Color.white);
                     }
                             if(object.equals("a3")){
                         salon3.jButton3.setBackground(Color.white);
                     }
                               if(object.equals("a4")){
                         salon3.jButton4.setBackground(Color.white);
                     }
                                 if(object.equals("b1")){
                         salon3.jButton5.setBackground(Color.white);
                                 }
                           if(object.equals("b2")){
                         salon3.jButton6.setBackground(Color.white);
                     }
                             if(object.equals("b3")){
                         salon3.jButton7.setBackground(Color.white);
                     }
                               if(object.equals("b4")){
                         salon3.jButton8.setBackground(Color.white);
                     }
                                 if(object.equals("c1")){
                         salon3.jButton9.setBackground(Color.white);
                     }
                         if(object.equals("c2")){
                             salon3.jButton10.setBackground(Color.white);
                         }
                           if(object.equals("c3")){
                         salon3.jButton11.setBackground(Color.white);
                     }
                             if(object.equals("c4")){
                         salon3.jButton12.setBackground(Color.white);
                     }
                               if(object.equals("d1")){
                         salon3.jButton13.setBackground(Color.white);
                     }
                                 if(object.equals("d2")){
                         salon3.jButton14.setBackground(Color.white);
                     }
                                   if(object.equals("d3")){
                         salon3.jButton15.setBackground(Color.white);
                     }
                                     if(object.equals("d4")){
                         salon3.jButton16.setBackground(Color.white);
                     }
                    }catch(Exception exception){
                             System.out.print(exception);
                             }
                    }
                 
              } catch (SQLException ex) {
                   System.out.println(ex);
                }finally{
            try {
                connection.close();
                statement.close();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
              }
       }
        else if(jTxtId.getText().equals("4")){
       Salon4 salon4 = new Salon4();
       salon4.setVisible(true);
       salon4.pack();
       salon4.setLocationRelativeTo(null);
       salon4.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
        Connection connection=null;
              DbHelper dbHelper= new DbHelper();
              Statement statement=null;
              ResultSet resultSet;
              try{
                  connection=dbHelper.getConnection();
                  String sql="select * from bilet where filmid='4'";
                  statement=connection.createStatement();
                  resultSet=statement.executeQuery(sql);
                  ArrayList<String> arrayList = new ArrayList<>();
                  int sayac=0;
                  while(resultSet.next()){
                      arrayList.add(resultSet.getString("koltukno"));
                      sayac++;
                  }
                 for(Object object:arrayList){
                    try{
                         if(object.equals("a1")){
                         salon4.jButtonA1.setBackground(Color.white);
                     }
                           if(object.equals("a2")){
                         salon4.jButtonA2.setBackground(Color.white);
                     }
                             if(object.equals("a3")){
                         salon4.jButton3.setBackground(Color.white);
                     }
                               if(object.equals("a4")){
                         salon4.jButton4.setBackground(Color.white);
                     }
                                 if(object.equals("b1")){
                         salon4.jButton5.setBackground(Color.white);
                                 }
                           if(object.equals("b2")){
                         salon4.jButton6.setBackground(Color.white);
                     }
                             if(object.equals("b3")){
                         salon4.jButton7.setBackground(Color.white);
                     }
                               if(object.equals("b4")){
                         salon4.jButton8.setBackground(Color.white);
                     }
                                 if(object.equals("c1")){
                         salon4.jButton9.setBackground(Color.white);
                     }
                         if(object.equals("c2")){
                             salon4.jButton10.setBackground(Color.white);
                         }
                           if(object.equals("c3")){
                         salon4.jButton11.setBackground(Color.white);
                     }
                             if(object.equals("c4")){
                         salon4.jButton12.setBackground(Color.white);
                     }
                               if(object.equals("d1")){
                         salon4.jButton13.setBackground(Color.white);
                     }
                                 if(object.equals("d2")){
                         salon4.jButton14.setBackground(Color.white);
                     }
                                   if(object.equals("d3")){
                         salon4.jButton15.setBackground(Color.white);
                     }
                                     if(object.equals("d4")){
                         salon4.jButton16.setBackground(Color.white);
                     }
                    }catch(Exception exception){
                             System.out.print(exception);
                             }
                    }
                 
              } catch (SQLException ex) {
                   System.out.println(ex);
                }finally{
            try {
                connection.close();
                statement.close();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
              }
       }
       else{
           JOptionPane.showMessageDialog(this,"Böyle bir salon bulunamadı lütfen doğru ID giriniz!");
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdActionPerformed

    private void jTxtAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hosgeldiniz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hosgeldiniz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hosgeldiniz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hosgeldiniz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hosgeldiniz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jFilmTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAd;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtKoltuk;
    private javax.swing.JTextField jTxtSearchKey;
    private javax.swing.JTextField jTxtSoyad;
    // End of variables declaration//GEN-END:variables
}
