/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erenk
 */
public class Salon4 extends javax.swing.JFrame {

    /**
     * Creates new form Salon4
     */
    public Salon4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonA1 = new javax.swing.JButton();
        jButtonA2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(938, 539));
        jPanel1.setMinimumSize(new java.awt.Dimension(938, 539));
        jPanel1.setLayout(null);

        jButtonA1.setBackground(java.awt.Color.red);
        jButtonA1.setText("A1");
        jButtonA1.setPreferredSize(new java.awt.Dimension(100, 70));
        jButtonA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonA1);
        jButtonA1.setBounds(96, 25, 110, 71);

        jButtonA2.setBackground(java.awt.Color.red);
        jButtonA2.setText("A2");
        jButtonA2.setPreferredSize(new java.awt.Dimension(100, 70));
        jButtonA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonA2);
        jButtonA2.setBounds(294, 25, 110, 71);

        jButton3.setBackground(java.awt.Color.red);
        jButton3.setText("A3");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton3);
        jButton3.setBounds(489, 25, 110, 71);

        jButton4.setBackground(java.awt.Color.red);
        jButton4.setText("A4");
        jButton4.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton4);
        jButton4.setBounds(700, 30, 100, 71);

        jButton5.setBackground(java.awt.Color.red);
        jButton5.setText("B1");
        jButton5.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton5);
        jButton5.setBounds(96, 141, 110, 69);

        jButton6.setBackground(java.awt.Color.red);
        jButton6.setText("B2");
        jButton6.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton6);
        jButton6.setBounds(294, 141, 110, 69);

        jButton7.setBackground(java.awt.Color.red);
        jButton7.setText("B3");
        jButton7.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(489, 138, 110, 74);

        jButton8.setBackground(java.awt.Color.red);
        jButton8.setText("B4");
        jButton8.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton8);
        jButton8.setBounds(699, 141, 100, 69);

        jButton9.setBackground(java.awt.Color.red);
        jButton9.setText("C1");
        jButton9.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton9);
        jButton9.setBounds(96, 270, 110, 76);

        jButton10.setBackground(java.awt.Color.red);
        jButton10.setText("C2");
        jButton10.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton10);
        jButton10.setBounds(294, 270, 110, 76);

        jButton11.setBackground(java.awt.Color.red);
        jButton11.setText("C3");
        jButton11.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(491, 273, 110, 76);

        jButton12.setBackground(java.awt.Color.red);
        jButton12.setText("C4");
        jButton12.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton12);
        jButton12.setBounds(700, 270, 100, 76);

        jButton13.setBackground(java.awt.Color.red);
        jButton13.setText("D1");
        jButton13.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton13);
        jButton13.setBounds(96, 431, 110, 80);

        jButton14.setBackground(java.awt.Color.red);
        jButton14.setText("D2");
        jButton14.setPreferredSize(new java.awt.Dimension(100, 70));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(294, 431, 110, 80);

        jButton15.setBackground(java.awt.Color.red);
        jButton15.setText("D3");
        jButton15.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton15);
        jButton15.setBounds(489, 436, 110, 72);

        jButton16.setBackground(java.awt.Color.red);
        jButton16.setText("D4");
        jButton16.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.add(jButton16);
        jButton16.setBounds(697, 431, 100, 80);

        jButton1.setBackground(java.awt.Color.red);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 73, 25);

        jButton18.setBackground(java.awt.Color.red);
        jPanel1.add(jButton18);
        jButton18.setBounds(837, 25, 91, 44);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("    DOLU");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(837, 186, 79, 22);

        jButton19.setBackground(java.awt.Color.white);
        jPanel1.add(jButton19);
        jButton19.setBounds(837, 132, 91, 36);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("   BOŞ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(839, 87, 81, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sinemaa.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 970, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonA1ActionPerformed
        
    }//GEN-LAST:event_jButtonA1ActionPerformed

    private void jButtonA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonA2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Hosgeldiniz().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salon4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salon4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salon4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salon4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salon4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton10;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton14;
    public static javax.swing.JButton jButton15;
    public static javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JButton jButton9;
    public static javax.swing.JButton jButtonA1;
    public static javax.swing.JButton jButtonA2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
