/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erenk
 */
public class Salon2 extends javax.swing.JFrame {

    /**
     * Creates new form Salon2
     */
    public Salon2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(938, 539));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(java.awt.Color.red);
        jButton1.setText("A1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 28, 111, 61));

        jButton2.setBackground(java.awt.Color.red);
        jButton2.setText("A2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 28, 114, 61));

        jButton3.setBackground(java.awt.Color.red);
        jButton3.setText("A3");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 28, 125, 61));

        jButton4.setBackground(java.awt.Color.red);
        jButton4.setText("A4");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 28, 118, 61));

        jButton5.setBackground(java.awt.Color.red);
        jButton5.setText("B1");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 146, 111, 69));

        jButton6.setBackground(java.awt.Color.red);
        jButton6.setText("B2");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 146, 114, 69));

        jButton7.setBackground(java.awt.Color.red);
        jButton7.setText("B3");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 146, 123, 69));

        jButton8.setBackground(java.awt.Color.red);
        jButton8.setText("B4");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 146, 118, 69));

        jButton9.setBackground(java.awt.Color.red);
        jButton9.setText("C1");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 271, 111, 76));

        jButton10.setBackground(java.awt.Color.red);
        jButton10.setText("C2");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 271, 114, 76));

        jButton11.setBackground(java.awt.Color.red);
        jButton11.setText("C3");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 271, 125, 76));

        jButton12.setBackground(java.awt.Color.red);
        jButton12.setText("C4");
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 271, 118, 76));

        jButton13.setBackground(java.awt.Color.red);
        jButton13.setText("D1");
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 399, 111, 80));

        jButton14.setBackground(java.awt.Color.red);
        jButton14.setText("D2");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 399, 114, 80));

        jButton15.setBackground(java.awt.Color.red);
        jButton15.setText("D3");
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 399, 125, 80));

        jButton16.setBackground(java.awt.Color.red);
        jButton16.setText("D4");
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 399, 126, 80));

        jButton17.setBackground(java.awt.Color.red);
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setText("<");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 79, -1));

        jButton18.setBackground(java.awt.Color.red);
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 27, 91, 29));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("    DOLU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 166, 79, -1));

        jButton19.setBackground(java.awt.Color.white);
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 107, 91, 36));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("   BOŞ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 62, 81, 27));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sinemaa.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new Hosgeldiniz().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salon2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salon2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salon2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salon2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salon2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton10;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton14;
    public static javax.swing.JButton jButton15;
    public static javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
